- name: check if DB exists
  # Note: get-db-config already verified that db_name requires no quoting (Bobby Tables)
  shell: |
    if command -v psql >/dev/null; then
      psql --tuples-only --no-align \
        --username={{ db_user | quote }} \
        --host={{ db_host | quote }} \
        --port={{ db_port | quote }} \
        --dbname=postgres \
        --command="SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'"
    fi
  environment:
    PGPASSWORD: "{{ db_password }}"
  register: db_exists
  changed_when: false
