- name: Prepare
  hosts: all
  gather_facts: false

  # Note that these tasks could also be in playbook.yml after the quickstart task.
  # But having them here allows to run `molecule verify -s quickstart` without having to wait for quickstart.sh
  tasks:
    - name: stop Django server
      include_role:
        name: app-server
        tasks_from: free-port
        vars_from: django

    - include_role:
        name: app-server
        tasks_from: start-server
        vars_from: django

    - name: stop Webpack server
      include_role:
        name: app-server
        tasks_from: free-port
        vars_from: webpack

    - include_role:
        name: app-server
        tasks_from: start-server
        vars_from: webpack

    - include_role:
        name: app-server
        tasks_from: check-crashed
        vars_from: django

    - include_role:
        name: app-server
        tasks_from: check-crashed
        vars_from: webpack
