- name: unmount bucket
  command: fusermount -u {{ s3_mountpoint.path }}
  failed_when: false    # ignore and continue with next task

- name: remove mountpoint
  command: rmdir {{ s3_mountpoint.path }}
  args:
    warn: no    # Suggests to use "file"  https://github.com/ansible/ansible/issues/22248
