- name: install Poetry and create virtualenv
  block:
    - name: install Poetry with pip as root
      pip:
        name: poetry
        executable: pip3
      become: yes
      register: poetry_install
      failed_when:
        - poetry_install is failed
        - "'Unable to find any of pip3 to use.' not in (poetry_install.msg | default(''))"
      # In CentOS it works the first time, but then fails in later plays.
      # "which pip3" --> "/usr/local/bin/pip3"
      # "sudo which pip3" --> "which: no pip3 in (/sbin:/bin:/usr/sbin:/usr/bin)"

    - name: sudo pip3 not found message
      debug:
        # Print debug message because previous task shows as "ok" if it failed
        msg: pip3 not found with sudo, retrying without sudo...
      when:
        - "'Unable to find any of pip3 to use.' in (poetry_install.msg | default(''))"

    - name: retry Poetry install without sudo
      pip:
        name: poetry
        executable: pip3
      when:
        - "'Unable to find any of pip3 to use.' in (poetry_install.msg | default(''))"

    - name: check if Poetry is available in path
      shell: command -v poetry  # noqa 305    "command" is a shell builtin, not an executable utility
      register: poetry_existence
      changed_when: False
      failed_when: False  # To fail with a custom message, in the next task

    - name: fail if Poetry is not available in path
      fail:
        msg: Poetry is installed but not available in path. Please try reinstalling manually.
      when: poetry_existence.rc > 0

    - name: get Poetry virtualenv
      command: poetry env info -p
      args:
        chdir: "{{ server_root_dir }}"
      register: venv
      changed_when: false
      failed_when: false
      tags: update

    - name: create virtualenv with Poetry
      command: poetry env use 3.8
      args:
        chdir: "{{ server_root_dir }}"
      when: venv.rc > 0

  when: ansible_distribution != 'MacOSX'

# Could avoid running twice with "when", but would have to register to another variable, and later choose between the two registered...
- name: get Poetry virtualenv again
  include_role:
    name: get-venv

- name: install Poetry requirements
  command: poetry install
  args:
    chdir: "{{ server_root_dir }}"
  # Improvement: idempotence (report task as "ok" instead of always as "changed")
