- name: install Poetry and create virtualenv
  block:
    - name: Install poetry with pip
      pip:
        name: poetry
        executable: pip3

    - name: check if Poetry is available in path
      shell: command -v poetry  # noqa 305    "command" is a shell builtin, not an executable utility
      register: poetry_existence
      changed_when: False
      failed_when: False  # To fail with a custom message, in the next task

    - name: fail if Poetry is not available in path
      fail:
        msg: Poetry is installed but not available in path. Please try reinstalling manually.
      when: poetry_existence.rc > 0

    - name: get Poetry virtualenv
      command: poetry env info -p
      args:
        chdir: "{{ server_root_dir }}"
      register: venv
      changed_when: false
      failed_when: false
      tags: update

    - name: create virtualenv with Poetry
      command: poetry env use 3.8
      args:
        chdir: "{{ server_root_dir }}"
      when: venv.rc > 0

  when: ansible_distribution != 'MacOSX'

# Could avoid running twice with "when", but would have to register to another variable, and later choose between the two registered...
- name: get Poetry virtualenv again
  include_role:
    name: get-venv

- name: install Poetry requirements
  command: poetry install
  args:
    chdir: "{{ server_root_dir }}"
  # Improvement: idempotence (report task as "ok" instead of always as "changed")
