- name: check if get-db-config should be skipped
  set_fact:
    skip_get_db_config: "{{ (skip_if_set | default(False)) and db_name is defined }}"
  # This extra task is required (to skip the following tasks that take longer),
  # because using "when: db_name is not defined" in the block applies "when" to all tasks,
  # so only the first one runs (db_name is not defined)
  # and the next ones are skipped (db_name IS defined).

- name: get DB configuration
  block:
    - name: get DB parameters
      include_tasks:    # It's not possible to loop over block
        file: get-parameter.yaml
        apply:
          no_log: "{{ item == 'db_password' }}"
      loop:
        - db_name
        - db_user
        - db_password
        - db_host
        - db_port
      # Improvement: parallelize.

    - name: verify database name
      assert:
        that: (db_name | quote) == db_name
        fail_msg: |
          db_name has characters that require quoting!
            {{ db_name }}
            {{ db_name | quote }}
        quiet: yes

  rescue:
    - name: "{{ failed_get_db_config_task_name }}"
      fail:
        msg: Failed to obtain database configuration. Make sure the project is set up correctly.

  when: not skip_get_db_config
