- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: set english environment locale
      import_tasks: ../utils/set-locale.yaml

    - name: Install Git and wget
      package:
        name:
          - git
          - wget
        state: present
      become: yes
